"use client"
import Head from 'next/head'
import { useState } from 'react'
import axios from 'axios'

export default function Home() {

  const [email, setEmail] = useState('')

  const templateId = "template_e7imjke";


  const SendMail = async (e) => {
    
    e.preventDefault()


  
    axios.post('http://localhost:3000/api/email', { email, templateId })
      .then(

        (res) => {
          alert('Başarıyla Gönderildi')
          setEmail('')
        }

      ).catch(
        (e) => alert("Hata")
      )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <form>
          <input type="text" placeholder="Write Something" required value={email} onChange={(e) => setEmail(e.target.value)}></input>
          <button onClick={SendMail}>Send</button>
        </form>
      </main>
    </div>
  )
}